#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hyprland.org/Configuring/Variables/

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    col.active_border   = rgba(9cdef2ff)
    col.inactive_border = rgba(444444ff)
    gaps_in             = 7 #05
    gaps_out            = 2 #20
    border_size         = 2
    resize_on_border    = false

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing       = false
    layout              = dwindle
}
