
# #######################################################################################
# PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hyprland.conf AND EDIT IT,
# OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
# #######################################################################################

source = ~/.config/hypr/modules/borders.conf
source = ~/.config/hypr/modules/monitors.conf
source = ~/.config/hypr/modules/env.conf
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/decoration.conf 
source = ~/.config/hypr/modules/animations.conf 
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/gestures.conf
source = ~/.config/hypr/modules/keybinds.conf
source = ~/.config/hypr/modules/windowrules.conf

# Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile     = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo   = false # If true disables the random hyprland logo / anime girl background. :(
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name        = epic-mouse-v1
    sensitivity = -0.5
}
