preload = ~/Pictures/Wallpapers/HDDesk2b.png
wallpaper = eDP-1, ~/Pictures/Wallpapers/HDDesk2b.png
#preload = ~/Pictures/Persona_5/persona-5-royal-sumire-yoshizawa-lwozfs6fzixsgnmk.jpg
#wallpaper = eDP-1, ~/Pictures/Persona_5/persona-5-royal-sumire-yoshizawa-lwozfs6fzixsgnmk.jpg


splash = false
