# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi
unset rc

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv bash)"

alias vim='nvim'
#alias rm='rm -Iv'
alias rm='trash -v'

export EDITOR=nvim
export JAVA_HOME=/var/home/gustavo/.java/jvm/jdk1.8.0
#export JAVA_HOME=$HOME/.jdks/corretto-11.0.28
export PATH="$JAVA_HOME/bin:$PATH"
export PATH="$HOME/.emacs.d/bin:$PATH"
